name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Ejecutar este workflow cuando se realice un push en la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Usar la versión más moderna de Node.js

      - name: Install dependencies
        run: yarn install

      - name: Convert line endings to Unix format
        run: find . -type f -print0 | xargs -0 dos2unix

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.YOUR_SECRET_NAME }}
          publish_dir: ./dist
          publish_branch: gh-pages  # Desplegar en la rama gh-pages
